### ISSUE TITLE
price pusher Error: gas required exceeds allowance

### ISSUE THREAD

**Issue by mookim-eth** [pyth-network/pyth-crosschain#807]
running on Aribtrum Goerli, which cost a lot of extra gas as its L1 georli gas price is too high now

```
Some of the above values passed the threshold. Will push the price.
Pushing  [
  '0xf9c0172ba10dfa4d19088d94f5bf61d3b54d5bd7483a322a982e1373ee8ea31b',
  '0x997e0bf451cb36b4aea096e6b5c254d700922211dd933d9d17c467f0d6f34321',
  '0x73dc009953c83c944690037ea477df627657f45c14f16ad3a61089c5a3f9f4f2',
  '0x31775e1d6897129e8a84eeba975778fb50015b88039e9bc140bbd839694ac0ae',
  '0x37f40d2898159e8f2e52b93cb78f47cc3829a31e525ab975c49cc5c5d9176378',
  '0xd2c2c1f2bba8e0964f9589e060c2ee97f5e19057267ac3284caef3bd50bd2cb5',
  '0xd7566a3ba7f7286ed54f4ae7e983f4420ae0b1e0f3892e11f9c4ab107bbad7b9',
  '0xbcbdc2755bd74a2065f9d3283c2b8acbd898e473bdb90a6764b3dbd467c56ecd',
  '0xc1b12769f6633798d45adfd62bfc70114839232e2949b01fb3d3f927d2606154',
  '0x2646ca1e1186fd2bb48b2ab3effa841d233b7e904b2caebb19c8030784a89c97',
  '0xb762d257b4bbce7935a8251b3e060977cfab1ed21770e8b431beff4cb7f41137'
]
Update fee: 6
Polled an EVM on chain price for feed BTC/USD (f9c0172ba10dfa4d19088d94f5bf61d3b54d5bd7483a322a982e1373ee8ea31b).
Polled an EVM on chain price for feed ETH/USD (ca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6).
Using gas price: 100000000 and nonce: 92
Polled an EVM on chain price for feed LTC/USD (997e0bf451cb36b4aea096e6b5c254d700922211dd933d9d17c467f0d6f34321).
An unidentified error has occured:
undefined
/code/lib/evm/evm.js:179
            throw err;
            ^

Error: gas required exceeds allowance (2087137016)
    at /code/node_modules/web3-provider-engine/subproviders/provider.js:19:36
    at /code/node_modules/web3-providers-http/lib/index.js:127:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

**Comment by jayantk** [comment]
hey @mookim-eth do you think the problem here is that the transaction is hitting the gas limit for the block? i.e., is the fix to break up the update into separate transactions?

**Comment by mookim-eth** [comment]
yep, deviding into multiple txs would be helpful

let me explain the situation:

>it's because goerli is too busy at that time, gas price about 6000 gwei
and arbitrum goerli takes this into calculation of gasLimit
basically as long as L1 is busy, L2 gas usage will be much higher, though gas price not change still 0.1gwei

**Comment by jayantk** [comment]
ok makes sense. we can set a maximum on the number of updates pushed in one tx or something.
